#137586733 Fixed accounts tests
andela/-healthchecks_blacklist pull request #6
Opened 2017-02-03 08:00 UTC by lederp23

2017-02-06 09:21 UTC, egichuri requested changes

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_check_token.py
> +        self.client.login(username="alice", password="password")
When this is done in the setup it means the user is logged in before each test runs. Better do this where it's required.

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_check_token.py
> +        self.profile.token = 'dcdf'
I don't think you need this. Test using one that's different from the one set in `SetUp`.

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_check_token.py
> +        payload = {"email":"alice@example.org", "password":"password"}
variable `payload` set but not used.

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_check_token.py
> +    # Login and test it redirects already logged in
Consider using Docstring conventions for comments.

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_check_token.py
> +        response = self.client.post("/accounts/check_token/alice/rgrn/")
(For practice/learning), use `reverse` for this url.

2017-02-06 09:21 UTC, egichuri commented on hc/accounts/tests/test_profile.py
> +        self.assertRedirects(r, "/accounts/set_password_link_sent/")
Would be important to use descriptive variable names.
You can also use reverse here.

2017-02-06 09:21 UTC, andela-egichuri commented on hc/accounts/tests/test_switch_team.py
> +        assert response.status_code == 403
Use unittest asserts

2017-02-06 09:22 UTC, andela-egichuri commented
@lederp23 Please change the base branch for the PR to `develop`

2017-02-07 22:38 UTC, andela-egichuri commented on hc/accounts/tests/test_check_token.py
> +        response = self.client.post(
This  response is for login. You're supposed to check the response for the next request when the user is already logged in.

2017-02-07 22:49 UTC, andela-egichuri commented on hc/accounts/tests/test_check_token.py
>          response = self.client.post("/accounts/check_token/alice/rgrn/")
Check the [docs](https://docs.djangoproject.com/en/1.10/ref/urlresolvers/#reverse) for `reverse` usage

2017-02-08 07:52 UTC, lederp23 commented on hc/accounts/tests/test_check_token.py
> +        response = self.client.post(
What kind of request are we supposed to make after login.

2017-02-08 07:59 UTC, andela-egichuri commented on hc/accounts/tests/test_check_token.py
> +        response = self.client.post(
@lederp23 You can make a get request to the login page and check the response.

2017-02-08 09:03 UTC, andela-egichuri commented on hc/accounts/tests/test_check_token.py
> +        response = self.client.post(
@lederp23 Ignore this. For the test to work we'd need to change the login endpoint which is beyond the scope of this task.

2017-02-08 09:29 UTC, egichuri approved these changes

2017-02-08 09:29 UTC, merged